#!/usr/bin/env python3
"""Generate the Ingredients catalogue from docs/data/ingredients/*.yaml.

Reads every YAML file in docs/data/ingredients/ (each may hold a single board
mapping, or a ``boards:`` list) and writes:

  * docs/ingredients/index.md — an overview with an at-a-glance table of every
    board, each linking to its detail on the relevant category page, and
  * docs/ingredients/<category>.md — one page per category (Mainboards, Power
    management, Actuators, Sensors, Utilities, Training) with the detail sections.

This keeps one source of truth (the YAML) for the overview table, the category
pages, and — later — the "ingredients used" lists on recipe pages. Every output
file carries a "do not edit" banner because it is overwritten on every run.

Recipe pages cross-link boards as ``../ingredients/<category>.md#<slug>``; the
mapping from slug to category page is defined here (see ``page_for``).

Run via ``uv run poe gen`` (also runs automatically before ``serve``/``build``).
"""

from __future__ import annotations

import csv
import sys
from pathlib import Path

import yaml

# This script lives at docs/scripts/, so ROOT is the docs/ directory itself.
ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "ingredients"
OUT_DIR = ROOT / "ingredients"

# Vendored Kitspace cache (populated by docs/scripts/sync_kitspace.py). Optional: if
# absent, boards simply render without a Bill of materials.
KITSPACE_DIR = ROOT / "data" / "kitspace"
KITSPACE_MANIFEST = KITSPACE_DIR / "manifest.yaml"
KITSPACE_BOM_DIR = KITSPACE_DIR / "bom"
REPO_BLOB = "https://github.com/BeeHive-org/BeeHive/blob/master"
REPO_TREE = "https://github.com/BeeHive-org/BeeHive/tree/master"
# Kitspace board pages (interactive BOM + one-click ordering); the manifest
# project key is the URL slug.
KITSPACE_BOARD = "https://kitspace.org/BeeHive-org/BeeHive"

# project key -> manifest entry; filled by load_kitspace() in main().
KITSPACE: dict[str, dict] = {}

# Category key -> (display label, page filename stem). Order sets display order.
CATEGORIES: list[tuple[str, str, str]] = [
    ("mainboard", "Mainboards", "mainboards"),
    ("power", "Power management", "power"),
    ("actuator", "Actuators", "actuators"),
    ("sensor", "Sensors", "sensors"),
    ("utility", "Utilities", "utilities"),
    ("training", "Training", "training"),
]
LABELS = {key: label for key, label, _ in CATEGORIES}
STEMS = {key: stem for key, _, stem in CATEGORIES}

# A one-line framing for each category page.
BLURBS = {
    "mainboard": (
        "The mainboard carries the microcontroller and breaks out every pin. "
        "Most builds need exactly one."
    ),
    "power": (
        "Power-management boards distribute and convert the 12 V supply so each "
        "part of a build gets the voltage and current it needs."
    ),
    "actuator": (
        "Actuator boards make things happen in the world — drive motors, "
        "solenoids, Peltier elements, and LEDs."
    ),
    "sensor": "Sensor boards read the world — gas, humidity, temperature, and infrared.",
    "utility": (
        "Utility boards condition or translate signals rather than driving an "
        "actuator or reading a sensor — the glue between other boards."
    ),
    "training": (
        "The Training board is for learning, not for a build — a testbed that "
        "gathers common components so you can master electronics and MicroPython "
        "one concept at a time. See the [Intro to Electronics course](../courses/intro-to-electronics/index.md)."
    ),
}

BANNER = (
    "<!-- AUTO-GENERATED by docs/scripts/build_ingredients.py — do not edit.\n"
    "     Edit the YAML in docs/data/ingredients/ and run `uv run poe gen`. -->\n"
)


def load_boards() -> list[dict]:
    """Collect every board mapping across all YAML files in DATA_DIR."""
    boards: list[dict] = []
    for path in sorted(DATA_DIR.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if isinstance(doc, list):
            boards.extend(doc)
        elif "boards" in doc:
            boards.extend(doc["boards"])
        else:
            boards.append(doc)
    return boards


def validate(boards: list[dict]) -> None:
    seen: set[str] = set()
    for b in boards:
        for field in ("slug", "name", "category", "function"):
            if not b.get(field):
                sys.exit(f"error: board {b.get('name', b)!r} is missing '{field}'")
        if b["slug"] in seen:
            sys.exit(f"error: duplicate slug {b['slug']!r}")
        seen.add(b["slug"])
        if b["category"] not in LABELS:
            sys.exit(
                f"error: board {b['name']!r} has unknown category "
                f"{b['category']!r} (expected one of {sorted(LABELS)})"
            )


def clean(text: str) -> str:
    """Collapse the whitespace YAML folded scalars leave behind."""
    return " ".join(str(text).split())


def load_kitspace() -> dict[str, dict]:
    """Load the vendored Kitspace manifest, or {} if it hasn't been synced."""
    if not KITSPACE_MANIFEST.exists():
        return {}
    manifest = yaml.safe_load(KITSPACE_MANIFEST.read_text(encoding="utf-8")) or {}
    return manifest.get("multi", {})


def read_bom(key: str) -> list[tuple[str, str, str]]:
    """Return (references, qty, description) rows from a vendored BOM CSV.

    The first three columns of every BeeHive `1-click-bom.csv` are References,
    Qty, Description; later manufacturer/MPN columns are inconsistent, so we link
    to the full CSV rather than trying to render them.
    """
    path = KITSPACE_BOM_DIR / f"{key}.csv"
    if not path.exists():
        return []
    text = path.read_text(encoding="utf-8", errors="replace")
    rows: list[tuple[str, str, str]] = []
    reader = csv.reader(text.splitlines())
    next(reader, None)  # header
    for row in reader:
        if len(row) < 3 or not row[0].strip():
            continue
        refs = ", ".join(r.strip() for r in row[0].split(";") if r.strip())
        # Some upstream CSVs already contain U+FFFD where a "µ" was lost (e.g.
        # the "33µH" inductor); restore it so the BOM reads correctly.
        desc = row[2].strip().replace("�", "µ")
        rows.append((refs, row[1].strip(), desc))
    return rows


def render_hardware(board: dict) -> str:
    """Fabrication-file links + a collapsible Bill of materials for a board.

    Returns "" when the board has no Kitspace project or the cache is absent.
    """
    key = board.get("kitspace")
    if not key or key not in KITSPACE:
        return ""
    proj = KITSPACE[key]

    # Kitspace is the primary "get this board" link: interactive BOM, gerber
    # preview, and one-click ordering from several fabs.
    links: list[str] = [f"[Order & BOM on Kitspace]({KITSPACE_BOARD}/{key})"]
    if proj.get("gerbers"):
        links.append(f"[Gerbers]({REPO_TREE}/{proj['gerbers']})")
    pcb = (proj.get("eda") or {}).get("pcb")
    if pcb:
        links.append(f"[KiCad PCB]({REPO_BLOB}/{pcb})")

    out: list[str] = []
    if links:
        out.append("**Hardware files:** " + " · ".join(links) + "\n")

    bom = read_bom(key)
    if bom:
        out.append(f'??? note "Bill of materials — {len(bom)} lines"\n')
        out.append("    | Ref | Qty | Description |")
        out.append("    | --- | --- | ----------- |")
        for refs, qty, desc in bom:
            out.append(f"    | {refs} | {qty} | {desc} |")
        out.append("")
    return "\n".join(out)


def page_for(board: dict) -> str:
    """The category page filename a board's detail lives on."""
    return f"{STEMS[board['category']]}.md"


def render_overview(by_category: dict[str, list[dict]]) -> str:
    out: list[str] = ["---\ntitle: Ingredients\n---\n", BANNER, "# Ingredients\n"]
    out.append(
        "Every BeeHive build is made from **ingredients**: a *mainboard* that "
        "carries the microcontroller, plus *daughter boards* that each do one "
        "job — drive an actuator or read a sensor. Combine them like a recipe to "
        "build an application. Each board follows the same 4-pin connector "
        "(two data lines, power, ground), so they mix and match freely.\n"
    )
    out.append("## Categories\n")
    for key, label, stem in CATEGORIES:
        count = len(by_category[key])
        if not count:
            continue
        noun = "board" if count == 1 else "boards"
        out.append(f"- **[{label}]({stem}.md)** — {BLURBS[key]} *({count} {noun})*")
    out.append("")

    out.append("## At a glance\n")
    out.append("| Board | Category | Function |")
    out.append("| ----- | -------- | -------- |")
    for key, label, stem in CATEGORIES:
        for b in by_category[key]:
            link = f"[{b['name']}]({stem}.md#{b['slug']})"
            out.append(f"| {link} | {label} | {clean(b['function'])} |")
    out.append("")
    return "\n".join(out) + "\n"


def render_category(key: str, label: str, group: list[dict]) -> str:
    out: list[str] = [f"---\ntitle: {label}\n---\n", BANNER, f"# {label}\n"]
    out.append(clean(BLURBS[key]) + "\n")
    for b in group:
        out.append(f"## {b['name']} {{ #{b['slug']} }}\n")
        if b.get("image"):
            out.append(f"![{b['name']}]({b['image']}){{ width=280 }}\n")
        if b.get("description"):
            out.append(clean(b["description"]) + "\n")
        rows: list[tuple[str, str]] = []
        if b.get("components"):
            rows.append(("Key parts", ", ".join(b["components"])))
        if b.get("power"):
            rows.append(("Power", clean(b["power"])))
        if b.get("size"):
            rows.append(("Size", b["size"]))
        if b.get("repo"):
            rows.append(("Details", f"[Board page & schematics]({b['repo']})"))
        if rows:
            out.append("| | |")
            out.append("| --- | --- |")
            for name, value in rows:
                out.append(f"| **{name}** | {value} |")
            out.append("")
        hardware = render_hardware(b)
        if hardware:
            out.append(hardware)
    return "\n".join(out) + "\n"


def main() -> None:
    if not DATA_DIR.exists():
        sys.exit(f"error: {DATA_DIR} does not exist")
    boards = load_boards()
    if not boards:
        sys.exit(f"error: no boards found in {DATA_DIR}")
    validate(boards)

    KITSPACE.update(load_kitspace())

    by_category: dict[str, list[dict]] = {key: [] for key, _, _ in CATEGORIES}
    for b in boards:
        by_category[b["category"]].append(b)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "index.md").write_text(render_overview(by_category), encoding="utf-8")
    pages = 1
    for key, label, stem in CATEGORIES:
        group = by_category[key]
        if not group:
            continue
        (OUT_DIR / f"{stem}.md").write_text(
            render_category(key, label, group), encoding="utf-8"
        )
        pages += 1
    print(f"Generated {pages} Ingredients pages from {len(boards)} boards.")


if __name__ == "__main__":
    main()
