#!/usr/bin/env python3
"""Generate the Ingredients catalogue from data/ingredients/*.yaml.

Reads every YAML file in data/ingredients/ (each may hold a single board
mapping, or a ``boards:`` list) and writes a single generated page,
docs/ingredients/index.md, containing:

  * a short intro,
  * a summary table grouped by category, linking to per-board anchors, and
  * a detail section per board.

This keeps one source of truth (the YAML) for the master table, the board
pages, and — later — the "ingredients used" lists on recipe pages. The output
file carries a "do not edit" banner because it is overwritten on every run.

Run via ``uv run poe gen`` (also runs automatically before ``serve``/``build``).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "ingredients"
OUT_FILE = ROOT / "docs" / "ingredients" / "index.md"

# Display order + human labels for the category groupings.
CATEGORIES: list[tuple[str, str]] = [
    ("mainboard", "Mainboards"),
    ("power", "Power management"),
    ("actuator", "Actuators"),
    ("sensor", "Sensors"),
    ("control", "Control"),
]

BANNER = (
    "<!-- AUTO-GENERATED by scripts/build_ingredients.py — do not edit.\n"
    "     Edit the YAML in data/ingredients/ and run `uv run poe gen`. -->\n"
)


def load_boards() -> list[dict]:
    """Collect every board mapping across all YAML files in DATA_DIR."""
    boards: list[dict] = []
    for path in sorted(DATA_DIR.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if isinstance(doc, list):
            boards.extend(doc)
        elif "boards" in doc:
            boards.extend(doc["boards"])
        else:
            boards.append(doc)
    return boards


def validate(boards: list[dict]) -> None:
    seen: set[str] = set()
    valid_categories = {key for key, _ in CATEGORIES}
    for b in boards:
        for field in ("slug", "name", "category", "function"):
            if not b.get(field):
                sys.exit(f"error: board {b.get('name', b)!r} is missing '{field}'")
        if b["slug"] in seen:
            sys.exit(f"error: duplicate slug {b['slug']!r}")
        seen.add(b["slug"])
        if b["category"] not in valid_categories:
            sys.exit(
                f"error: board {b['name']!r} has unknown category "
                f"{b['category']!r} (expected one of {sorted(valid_categories)})"
            )


def clean(text: str) -> str:
    """Collapse the whitespace YAML folded scalars leave behind."""
    return " ".join(str(text).split())


def render(boards: list[dict]) -> str:
    by_category: dict[str, list[dict]] = {key: [] for key, _ in CATEGORIES}
    for b in boards:
        by_category[b["category"]].append(b)

    # Front-matter must be the first thing in the file, so the banner follows it.
    out: list[str] = ["---\ntitle: Ingredients\n---\n"]
    out.append(BANNER)
    out.append("# Ingredients\n")
    out.append(
        "Every BeeHive build is made from **ingredients**: a *mainboard* that "
        "carries the microcontroller, plus *daughter boards* that each do one "
        "job — drive an actuator or read a sensor. Combine them like a recipe to "
        "build an application. Each board follows the same 4-pin connector "
        "(two data lines, power, ground), so they mix and match freely.\n"
    )
    out.append(
        '!!! tip "This page is generated"\n'
        "    The catalogue below is built from `data/ingredients/*.yaml`. To add "
        "or correct a board, edit the YAML and run `uv run poe gen` — never edit "
        "this page by hand.\n"
    )

    # --- Summary table ---------------------------------------------------
    out.append("## At a glance\n")
    out.append("| Board | Category | Function | Size |")
    out.append("| ----- | -------- | -------- | ---- |")
    for key, label in CATEGORIES:
        for b in by_category[key]:
            link = f"[{b['name']}](#{b['slug']})"
            out.append(
                f"| {link} | {label} | {clean(b['function'])} | {b.get('size') or '—'} |"
            )
    out.append("")

    # --- Detail sections -------------------------------------------------
    for key, label in CATEGORIES:
        group = by_category[key]
        if not group:
            continue
        out.append(f"## {label}\n")
        for b in group:
            out.append(f"### {b['name']} {{ #{b['slug']} }}\n")
            if b.get("image"):
                out.append(f"![{b['name']}]({b['image']}){{ width=280 }}\n")
            if b.get("description"):
                out.append(clean(b["description"]) + "\n")
            rows: list[tuple[str, str]] = []
            if b.get("components"):
                rows.append(("Key parts", ", ".join(b["components"])))
            if b.get("power"):
                rows.append(("Power", clean(b["power"])))
            if b.get("size"):
                rows.append(("Size", b["size"]))
            if b.get("repo"):
                rows.append(("Details", f"[Board page & schematics]({b['repo']})"))
            if rows:
                out.append("| | |")
                out.append("| --- | --- |")
                for name, value in rows:
                    out.append(f"| **{name}** | {value} |")
                out.append("")

    return "\n".join(out) + "\n"


def main() -> None:
    if not DATA_DIR.exists():
        sys.exit(f"error: {DATA_DIR} does not exist")
    boards = load_boards()
    if not boards:
        sys.exit(f"error: no boards found in {DATA_DIR}")
    validate(boards)
    OUT_FILE.parent.mkdir(parents=True, exist_ok=True)
    OUT_FILE.write_text(render(boards), encoding="utf-8")
    print(f"Generated {OUT_FILE.relative_to(ROOT)} with {len(boards)} boards.")


if __name__ == "__main__":
    main()
