#!/usr/bin/env python3
"""Generate the Ingredients catalogue from data/ingredients/*.yaml.

Reads every YAML file in data/ingredients/ (each may hold a single board
mapping, or a ``boards:`` list) and writes:

  * docs/ingredients/index.md — an overview with an at-a-glance table of every
    board, each linking to its detail on the relevant category page, and
  * docs/ingredients/<category>.md — one page per category (Mainboards, Power
    management, Actuators, Sensors, Utilities) with the detail sections.

This keeps one source of truth (the YAML) for the overview table, the category
pages, and — later — the "ingredients used" lists on recipe pages. Every output
file carries a "do not edit" banner because it is overwritten on every run.

Recipe pages cross-link boards as ``../ingredients/<category>.md#<slug>``; the
mapping from slug to category page is defined here (see ``page_for``).

Run via ``uv run poe gen`` (also runs automatically before ``serve``/``build``).
"""

from __future__ import annotations

import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parent.parent
DATA_DIR = ROOT / "data" / "ingredients"
OUT_DIR = ROOT / "docs" / "ingredients"

# Category key -> (display label, page filename stem). Order sets display order.
CATEGORIES: list[tuple[str, str, str]] = [
    ("mainboard", "Mainboards", "mainboards"),
    ("power", "Power management", "power"),
    ("actuator", "Actuators", "actuators"),
    ("sensor", "Sensors", "sensors"),
    ("utility", "Utilities", "utilities"),
    ("training", "Training", "training"),
]
LABELS = {key: label for key, label, _ in CATEGORIES}
STEMS = {key: stem for key, _, stem in CATEGORIES}

# A one-line framing for each category page.
BLURBS = {
    "mainboard": (
        "The mainboard carries the microcontroller and breaks out every pin. "
        "Most builds need exactly one."
    ),
    "power": (
        "Power-management boards distribute and convert the 12 V supply so each "
        "part of a build gets the voltage and current it needs."
    ),
    "actuator": (
        "Actuator boards make things happen in the world — drive motors, "
        "solenoids, Peltier elements, and LEDs."
    ),
    "sensor": "Sensor boards read the world — gas, humidity, temperature, and infrared.",
    "utility": (
        "Utility boards condition or translate signals rather than driving an "
        "actuator or reading a sensor — the glue between other boards."
    ),
    "training": (
        "The Training board is for learning, not for a build — a testbed that "
        "gathers common components so you can master electronics and MicroPython "
        "one concept at a time. See the [Intro to electronics course](../courses/intro-to-electronics.md)."
    ),
}

BANNER = (
    "<!-- AUTO-GENERATED by scripts/build_ingredients.py — do not edit.\n"
    "     Edit the YAML in data/ingredients/ and run `uv run poe gen`. -->\n"
)


def load_boards() -> list[dict]:
    """Collect every board mapping across all YAML files in DATA_DIR."""
    boards: list[dict] = []
    for path in sorted(DATA_DIR.glob("*.yaml")):
        doc = yaml.safe_load(path.read_text(encoding="utf-8")) or {}
        if isinstance(doc, list):
            boards.extend(doc)
        elif "boards" in doc:
            boards.extend(doc["boards"])
        else:
            boards.append(doc)
    return boards


def validate(boards: list[dict]) -> None:
    seen: set[str] = set()
    for b in boards:
        for field in ("slug", "name", "category", "function"):
            if not b.get(field):
                sys.exit(f"error: board {b.get('name', b)!r} is missing '{field}'")
        if b["slug"] in seen:
            sys.exit(f"error: duplicate slug {b['slug']!r}")
        seen.add(b["slug"])
        if b["category"] not in LABELS:
            sys.exit(
                f"error: board {b['name']!r} has unknown category "
                f"{b['category']!r} (expected one of {sorted(LABELS)})"
            )


def clean(text: str) -> str:
    """Collapse the whitespace YAML folded scalars leave behind."""
    return " ".join(str(text).split())


def page_for(board: dict) -> str:
    """The category page filename a board's detail lives on."""
    return f"{STEMS[board['category']]}.md"


def render_overview(by_category: dict[str, list[dict]]) -> str:
    out: list[str] = ["---\ntitle: Ingredients\n---\n", BANNER, "# Ingredients\n"]
    out.append(
        "Every BeeHive build is made from **ingredients**: a *mainboard* that "
        "carries the microcontroller, plus *daughter boards* that each do one "
        "job — drive an actuator or read a sensor. Combine them like a recipe to "
        "build an application. Each board follows the same 4-pin connector "
        "(two data lines, power, ground), so they mix and match freely.\n"
    )
    out.append("## Categories\n")
    for key, label, stem in CATEGORIES:
        count = len(by_category[key])
        if not count:
            continue
        noun = "board" if count == 1 else "boards"
        out.append(f"- **[{label}]({stem}.md)** — {BLURBS[key]} *({count} {noun})*")
    out.append("")

    out.append("## At a glance\n")
    out.append("| Board | Category | Function | Size |")
    out.append("| ----- | -------- | -------- | ---- |")
    for key, label, stem in CATEGORIES:
        for b in by_category[key]:
            link = f"[{b['name']}]({stem}.md#{b['slug']})"
            out.append(
                f"| {link} | {label} | {clean(b['function'])} | {b.get('size') or '—'} |"
            )
    out.append("")
    return "\n".join(out) + "\n"


def render_category(key: str, label: str, group: list[dict]) -> str:
    out: list[str] = [f"---\ntitle: {label}\n---\n", BANNER, f"# {label}\n"]
    out.append(clean(BLURBS[key]) + "\n")
    for b in group:
        out.append(f"## {b['name']} {{ #{b['slug']} }}\n")
        if b.get("image"):
            out.append(f"![{b['name']}]({b['image']}){{ width=280 }}\n")
        if b.get("description"):
            out.append(clean(b["description"]) + "\n")
        rows: list[tuple[str, str]] = []
        if b.get("components"):
            rows.append(("Key parts", ", ".join(b["components"])))
        if b.get("power"):
            rows.append(("Power", clean(b["power"])))
        if b.get("size"):
            rows.append(("Size", b["size"]))
        if b.get("repo"):
            rows.append(("Details", f"[Board page & schematics]({b['repo']})"))
        if rows:
            out.append("| | |")
            out.append("| --- | --- |")
            for name, value in rows:
                out.append(f"| **{name}** | {value} |")
            out.append("")
    return "\n".join(out) + "\n"


def main() -> None:
    if not DATA_DIR.exists():
        sys.exit(f"error: {DATA_DIR} does not exist")
    boards = load_boards()
    if not boards:
        sys.exit(f"error: no boards found in {DATA_DIR}")
    validate(boards)

    by_category: dict[str, list[dict]] = {key: [] for key, _, _ in CATEGORIES}
    for b in boards:
        by_category[b["category"]].append(b)

    OUT_DIR.mkdir(parents=True, exist_ok=True)
    (OUT_DIR / "index.md").write_text(render_overview(by_category), encoding="utf-8")
    pages = 1
    for key, label, stem in CATEGORIES:
        group = by_category[key]
        if not group:
            continue
        (OUT_DIR / f"{stem}.md").write_text(
            render_category(key, label, group), encoding="utf-8"
        )
        pages += 1
    print(f"Generated {pages} Ingredients pages from {len(boards)} boards.")


if __name__ == "__main__":
    main()
